#!/bin/bash
set -e

# Create necessary directories with proper permissions
echo "Creating directories..."
mkdir -p /var/www/html/bcoem/site
mkdir -p /var/www/html/bcoem/user_images
mkdir -p /var/www/html/bcoem/user_docs
mkdir -p /var/www/html/bcoem/includes

# Set proper permissions
echo "Setting permissions..."
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
chmod -R 777 /var/www/html/bcoem/user_images
chmod -R 777 /var/www/html/bcoem/user_docs

# Check if BCOE&M files exist
if [ ! -f /var/www/html/bcoem/index.php ]; then
    echo "WARNING: BCOE&M files not found in /var/www/html/bcoem/"
    echo "Please make sure you've extracted the BCOE&M files into the ./bcoem directory"
    # Create a simple index.php for testing
    echo "<?php phpinfo(); ?>" > /var/www/html/bcoem/index.php
    chown www-data:www-data /var/www/html/bcoem/index.php
fi

# Create a root index.php that redirects to /bcoem
echo "<?php header('Location: /bcoem/'); exit; ?>" > /var/www/html/index.php
chown www-data:www-data /var/www/html/index.php

# Wait for MySQL to be ready
echo "Waiting for MySQL to be ready..."
until mysql -h"${DB_HOST:-db}" -u"${DB_USER:-bcoem_user}" -p"${DB_PASSWORD:-bcoem_password}" -e "SELECT 1" > /dev/null 2>&1; do
    echo "MySQL is unavailable - sleeping"
    sleep 2
done
echo "MySQL is ready!"

# Create config.php if it doesn't exist
if [ ! -f /var/www/html/bcoem/site/config.php ]; then
    echo "Creating config.php..."
    cat > /var/www/html/bcoem/site/config.php <<'EOF'
<?php
/**
 * BCOE&M Configuration File
 * Auto-generated by Docker
 */

$hostname = "db";
$username = "bcoem_user";
$password = "bcoem_password";
$database = "bcoem";
$connection = new mysqli($hostname, $username, $password, $database);
$brewing = $connection;

$images_dir = dirname( __FILE__ );
$prefix = "bcoem_";
$installation_id = "<?php echo bin2hex(random_bytes(8)); ?>";
$session_expire_after = "30";

// IMPORTANT: Change this to FALSE after completing setup!
$setup_free_access = TRUE;

$sub_directory = "/bcoem";

// Force the correct port in URLs
if ($_SERVER['SERVER_PORT'] == '80' && strpos($_SERVER['HTTP_HOST'], ':8080') === false) {
    $_SERVER['HTTP_HOST'] = 'localhost:8080';
    $_SERVER['SERVER_PORT'] = '8080';
}

$base_url = "http://".$_SERVER['HTTP_HOST'].$sub_directory."/";
$server_root = $_SERVER['DOCUMENT_ROOT'];
?>
EOF
    chown www-data:www-data /var/www/html/bcoem/site/config.php
    chmod 644 /var/www/html/bcoem/site/config.php
fi

# Enable error logging
echo "Enabling error logging..."
echo "error_log = /var/log/php_errors.log" >> /usr/local/etc/php/conf.d/errors.ini
touch /var/log/php_errors.log
chown www-data:www-data /var/log/php_errors.log

# Start PHP-FPM
echo "Starting PHP-FPM..."
exec "$@"
