<?php
/**
 * BCOE&M Configuration File
 * Auto-generated by Docker
 */

$hostname = "db";
$username = "bcoem_user";
$password = "bcoem_password";
$database = "bcoem";
$connection = new mysqli($hostname, $username, $password, $database);
$brewing = $connection;

$images_dir = dirname( __FILE__ );
$prefix = "bcoem_";
$installation_id = "47919dbf8cdee45c";
$session_expire_after = "30";
$setup_free_access = FALSE;
$sub_directory = "/bcoem";
$base_url = "http://$_SERVER[SERVER_NAME]:$_SERVER[SERVER_PORT]$sub_directory/";
$server_root = $_SERVER['DOCUMENT_ROOT'];
?>
